export const vulnSyncEnvironments = {
    computerCommonUrl : 'http://localhost:8081/api/computers',
    getComputers:'http://localhost:8081/api/allComputers',
    getComputersByUuid: 'http://localhost:8081/api/uuid/computer',
    deActivateComputer: 'http://localhost:8081/api/computer/deactivate',
    deletedComputers: 'http://localhost:8081/api/computers/by-deletion-status',
    activeComputersList: 'http://localhost:8081/api/computers/by-activation-status',
    activateComputer: 'http://localhost:8081/api/computer/activate',
    applicationCommonUrl : 'http://localhost:8081/api/applications',
    getApplicationVulnerabilities: 'http://localhost:8081/api/applications/',
    getApplicationByUuid: 'http://localhost:8081/api/uuid/application',
    getApplicationsUrl : 'http://localhost:8081/api/applications',
    dependenciesCommonUrl : 'http://localhost:8081/api/dependency',
    getAllDependenciesUrl : 'http://localhost:8081/api/dependencies',
    getDependencyByUuid : 'http://localhost:8081/api/uuid/dependency',
    vulnerabilitiesCommonUrl: 'http://localhost:8081/api/vulnerability',
    getVulnerabilitiesUrl: 'http://localhost:8081/api/vulnerabilities',
    viewUnresolvedPageUrl: "http://localhost:8081/api/applications/unresolved-cpe",
    getLikelyCpeNames: "http://localhost:8081/api/hint/likelyCpeNames",
    addCpeHintUrl: "http://localhost:8081/api/hint/application/addHint"
}